name = "paseo-website"
account_id = "835cd580057df97323a7854a8069c5f1"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "./src/server-entry.ts"


[observability]
enabled = true

[[kv_namespaces]]
binding = "WEBSITE_CACHE"
id = "5d19976942be431b9cfbc83a0c2076b4"
