name = "paseo-relay"
account_id = "835cd580057df97323a7854a8069c5f1"
main = "src/cloudflare-adapter.ts"
compatibility_date = "2024-12-01"

routes = [{ pattern = "relay.paseo.zijieapi.de5.net", custom_domain = true }]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "RELAY"
class_name = "RelayDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RelayDurableObject"]
